### ISSUE TITLE
补丁管理平台对于不会写后台的人来说很有用，感谢

### ISSUE THREAD

**Issue by WadonLiu** [yanshuimu/MangoFixUtil#1]

**Comment by yanshuimu** [comment]
谢谢肯定！我会继续努力完善平台，使用过程中有问题欢迎来骚扰。

QQ：593692553
微信：hongguixu8131




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yanshuimu/MangoFixUtil"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月17日(星期一) 下午4:58
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[yanshuimu/MangoFixUtil] 补丁管理平台对于不会写后台的人来说很有用，感谢 (#1)
