### ISSUE TITLE
首页崩溃的话，无法通过服务端下载修复

### ISSUE THREAD

**Issue by q519776154** [yanshuimu/MangoFixUtil#4]
你好，我测试了一下，就是在app的首页，写了一个数组越界的崩溃，然后在demo.mg文件中写了修改的代码，使用你的远程下载方式，即使在didFinishLaunchingWithOptions这个方法里面，[[MangoFixUtil startWithAppId:AppID aesKey:AesKey] evalRemoteMangoScript];之后等待几秒，还是会崩溃

**Comment by yanshuimu** [comment]
请查看一下控制台打印信息，看下补丁是否执行成功，注意发布新补丁后，首次拉取后要重启APP才能生效。
控制台信息：
首次拉取补丁执行成功后会打印：The latest patch is successfully executed!  此时需重启APP。
后续执行成功会打印：The last patch is successfully executed!  无需重启APP。
